extension

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -32,21 +32,71 @@ jobs:
                       release-arch: aarch64
                       runner: [self-hosted, macOS, ARM64]
         steps:
-            - name: Checkout
+            - name: checkout
               uses: actions/checkout@v4
             - name: Install ${{ matrix.rust }} rust
               uses: dtolnay/rust-toolchain@master
               with:
                 toolchain: ${{ matrix.rust }}
-            - name: Install cargo-nextest
+            - name: install cargo-nextest
               uses: taiki-e/install-action@v2
               with:
                 tool: nextest
             - name: run tests
               run: |
-                cargo nextest run --workspace --all-features --lib --bins --tests --no-fail-fast
+                cargo nextest run --all-features --lib --bins --tests --no-fail-fast
               env:
                 RUST_LOG: "TRACE"
+            - name: build
+              run: |
+                cargo build --release
+                cargo run --features headers --bin generate_headers --release
+                cc -o main{,.c} -L target/release -l iroh_net_ffi -lSystem -lc -lm
+            - name: test run
+              run: |
+                ./main server --json > server_output.json &
+                # Wait for the server to start
+                sleep 2
+                # Read the second line of the file
+                line=$(sed -n '2p' server_output.json)
+                
+                # Check if the line is empty
+                if [[ -z "$line" ]]; then
+                    echo "Error: server_output.json does not have at least 2 lines"
+                    exit 1
+                fi
+                # Parse the JSON
+                json_output=$(echo $line | jq .)
+                
+                # Store variables
+                node_id=$(echo $json_output | jq -r '.node_id')
+                derp=$(echo $json_output | jq -r '.derp')
+                addrs=$(echo $json_output | jq -r '.addrs[]')
+                ./main client $node_id $derp ${addrs[@]}
+                sleep 1
+                
+                # Read the last line of the file
+                last_line=$(tail -n 1 server_output.json)
+                # Parse the JSON
+                json_output=$(echo $last_line | jq -r '.data')
+                # Ensure json_output is as expected
+                if [[ "$json_output" != "hello world from C" ]]; then
+                    echo "Error: Unexpected output"
+                    exit 1
+                fi
+                echo "Success"
+            - name: check headers
+              run: |
+                cp irohnet.h irohnet.h.orig
+                ./target/release/generate_headers
+                diff_output=$(diff irohnet.h irohnet.h.orig)
+                # Check if the diff_output is not empty
+                if [[ -n "$diff_output" ]]; then
+                    echo "Error: Differences were found compared to the checked in headers"
+                    exit 1
+                fi
+              env:
+                CARGO_CRATE_NAME: iroh-net-ffi
 
     cargo_deny:
         timeout-minutes: 30
@@ -56,7 +106,7 @@ jobs:
             - uses: actions/checkout@v3
             - uses: EmbarkStudios/cargo-deny-action@v1
               with:
-                arguments: --workspace --all-features
+                arguments: --all-features
                 command: check
                 command-arguments: "-Dwarnings"
     
