chore: upgrade to iroh-net 0.28.1 and quinn 0.12 (#32)
* upgrade to iroh-net 0.28.1 and quinn 0.12
* fix coordination issues in tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,12 +61,15 @@ jobs:
               env:
                 LD_LIBRARY_PATH: target/release
             - name: test run
+              id: run_tests
+              continue-on-error: true
               env:
                 LD_LIBRARY_PATH: target/release
               run: |
                 ./main server --json > server_output.json &
+                server_pid=$!
                 # Wait for the server to start
-                sleep 3
+                sleep 10
                 # Read the second line of the file
                 line=$(sed -n '2p' server_output.json)
 
@@ -87,13 +90,22 @@ jobs:
                 ./main client $node_id $relay ${addrs[@]}
                 sleep 10
 
+                # wait for server the shutdown
+                wait $server_pid
+                server_status=$?
+                echo ""
+                echo "Server closed with status $server_status"
+                if [[ "$server_status" != "0" ]]; then
+                  exit 1
+                fi
+
                 # Read the 3rd line of the file
                 last_line=$(sed -n '3p' server_output.json)
                 # Parse the JSON
                 json_output=$(echo $last_line | jq -r '.data')
                 # Ensure json_output is as expected
                 if [[ "$json_output" != "hello world from C" ]]; then
-                    echo "Error: Unexpected output"
+                    echo "Error: Unexpected output for line 3"
                     echo "server_output.json:"
                     cat server_output.json
                     exit 1
@@ -105,13 +117,22 @@ jobs:
                 json_output=$(echo $last_line | jq -r '.data')
                 # Ensure json_output is as expected
                 if [[ "$json_output" != "hello world from C" ]]; then
-                    echo "Error: Unexpected output"
+                    echo "Error: Unexpected output for line 6"
                     echo "server_output.json:"
                     cat server_output.json
                     exit 1
                 fi
 
+                echo ""
                 echo "Success"
+                echo "server_output.json:"
+                cat server_output.json
+            - name: Fail Job if Tests Failed
+              if: ${{ steps.run_tests.outcome == 'failure' }}
+              run: |
+                echo "Tests failed, server logs are:"
+                cat server_output.json
+                exit 1
             - name: check headers
               shell: bash
               run: |
@@ -179,10 +200,12 @@ jobs:
               env:
                 LD_LIBRARY_PATH: target/release
             - name: test run
+              id: run_tests
+              continue-on-error: true
               run: |
-                Start-Process -NoNewWindow -FilePath "./main.exe" -ArgumentList "server", "--json" -RedirectStandardOutput "server_output.json"
+                $server_process = Start-Process -PassThru -NoNewWindow -FilePath "./main.exe" -ArgumentList "server", "--json" -RedirectStandardOutput "server_output.json"
                 # Wait for the server to start
-                Start-Sleep -Seconds 3
+                Start-Sleep -Seconds 10
                 # Read the second line of the file
                 $line = Get-Content server_output.json | Select-Object -Index 1
 
@@ -199,7 +222,20 @@ jobs:
                 $relay = $json_output.relay
                 $addrs = $json_output.addrs
                 & "./main" "client" $node_id $relay $addrs
-                Start-Sleep -Seconds 3
+                Start-Sleep -Seconds 10
+
+                # wait for the server process to terminate
+                Wait-Process -InputObject $server_process
+
+                # # ramfox: ExitCode in windows seems to not work in all environments. I've tried a few variations, but they all show the exitCode as Null. commenting this out for now.
+                # $exitCode = $server_process.ExitCode
+
+                # Write-Output ""
+                # Write-Output "Server process exited with code: $exitCode"
+
+                # if ($exitCode -ne 0) {
+                #     exit 1
+                # }
 
                 # Read the 3rd line of the file
                 $last_line = Get-Content server_output.json | Select-Object -Index 2
@@ -207,7 +243,8 @@ jobs:
                 $json_output = ConvertFrom-Json $last_line
                 # Ensure json_output is as expected
                 if ($json_output.data -ne "hello world from C") {
-                    Write-Output "Error: Unexpected output"
+                    Write-Output "Error: Unexpected output for line 3"
+                    Write-Output $json_output
                     exit 1
                 }
 
@@ -217,10 +254,20 @@ jobs:
                 $json_output = ConvertFrom-Json $last_line
                 # Ensure json_output is as expected
                 if ($json_output.data -ne "hello world from C") {
-                    Write-Output "Error: Unexpected output"
+                    Write-Output "Error: Unexpected output for line 6"
+                    Write-Output $json_output
                     exit 1
                 }
+                Write-Output ""
                 Write-Output "Success"
+                Write-Output "server_output.json:"
+                Get-Content server_output.json
+            - name: Fail Job if Tests Failed
+              if: ${{ steps.run_tests.outcome == 'failure' }}
+              run: |
+                Write-Output "Tests failed, server logs are:"
+                Get-Content server_output.json
+                exit 1
 
     android_build:
         name: Android Build Only
